@Consilium = http://localhost:5202
# @Consilium = https://api.final.codyhowell.dev

@email = codyhowell44@gmail.com
@key = K4Yhc36WuskTT74007kT

###
POST {{Consilium}}/assignment
Email-Auth_Email: {{email}}
Email-Auth_ApiKey: {{key}}
Content-Type: application/json
{
    "Name": "lorem",
    "Description": "lorem description",
    "CourseId": "2",
    "DueDate": "2025-04-14T15:00:00",
    "DateStarted": "2025-04-14T16:00:00",
    "DateCompleted": "2025-04-14T17:00:00"
}

