@Consilium = https://consilium-api-cpgdcqaxepbyc2gj.westus3-01.azurewebsites.net
# @Consilium = http://localhost:5202
# @Consilium = https://api.final.codyhowell.dev

@email = tomaszeuskim@gmail.com
@key = 1MzeyKmpW2pdQEEOvgLE

###
POST {{Consilium}}/account?email={{email}}
###
GET {{Consilium}}/messages/all
Email-Auth_Email: {{email}}
Email-Auth_ApiKey: {{key}}
