@Consilium = http://localhost:5202
# @Consilium = https://api.final.codyhowell.dev

@email = codyhowell44@gmail.com
@key = mlurQfsQ_lsMe4Cp7oWn

###
POST {{Consilium}}/account?email={{email}}
###
GET {{Consilium}}/account/valid
Email-Auth_Email: {{email}}
Email-Auth_ApiKey: {{key}}
