@Consilium = http://localhost:5202
# @Consilium = https://api.final.codyhowell.dev

@email = codyhowell44@gmail.com
@key = K4Yhc36WuskTT74007kT

###
GET {{Consilium}}/account
###
POST {{Consilium}}/account?email={{email}}


