# @Consilium = http://localhost:5202
@Consilium = https://api.final.codyhowell.dev

@email = codyhowell44@gmail.com
@key = kwqXs7yPVrfkGnqfrL1m

###
GET {{Consilium}}/account
###
POST {{Consilium}}/account?email={{email}}


