apiVersion: apps/v1
kind: Deployment
metadata:
  name: consilium-api-dep
  namespace: consilium
spec:
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 0
  replicas: 3
  selector:
    matchLabels:
      app: consilium-api
  # pod below
  template:
    metadata:
      labels:
        app: consilium-api
    spec:
      containers:
      - name: consilium-api
        image: mateotomaszeuski/consilium:$BUILD_NUMBER
        # image: mateotomaszeuski/consilium:local_v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
          - name: DB_CONN
            value: "Host=consilium-postgres-svc;Port=5432;Username=consilium-admin;Password=mypassword;Database=consiliumdb"
          - name: OTEL_URL
            value: "http://consilium-otel-collector-svc:4317"
          - name: feature_flag
            value: "true"