apiVersion: apps/v1
kind: Deployment
metadata:
  name: consilium-postgres-dep
  namespace: $NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consilium-postgres
  template:
    metadata:
      labels:
        app: consilium-postgres
    spec:
      volumes:
        - name: consilium-postgres-data
          persistentVolumeClaim:
            claimName: consilium-postgres-pvc
        - name: consilium-postgres-backups
          persistentVolumeClaim:
            claimName: consilium-postgres-backups-pvc
      containers:
      - name: consilium-postgres
        volumeMounts:
          - name: consilium-postgres-data
            mountPath: /var/lib/postgresql/data
          - name: consilium-postgres-backups
            mountPath: /var/backups
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: consilium-admin
          - name: POSTGRES_PASSWORD
            value: mypassword
          - name: POSTGRES_DB
            value: consiliumdb