apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consilium-postgres-pvc
  namespace: consilium
spec:
  accessModes:
  - ReadWriteOnce
  # - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
