apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consilium-grafana-pvc
  namespace: $NAMESPACE
spec:
  accessModes:
  # - ReadWriteOnce
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
