apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consilium-otel-data-pvc
  namespace: $NAMESPACE
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi