apiVersion: v1
kind: Secret
metadata:
  namespace: $NAMESPACE
  name: consilium-secret-tls
type: kubernetes.io/tls
data:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDvjCCA0OgAwIBAgISBaLY1sk8uOwTDXTrRhgnyvo0MAoGCCqGSM49BAMDMDIx
    CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF
    NTAeFw0yNTA0MDgxOTAwNTZaFw0yNTA3MDcxOTAwNTVaMCIxIDAeBgNVBAMMFyou
    Y29uc2lsaXVtLmR1Y2tkbnMub3JnMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
    MN6ELbNHnVjZ4n7h+nYKhJnIp5anUhgv+/mzAJsuAiRvVGUZNg2JKjGNoNWsFy/y
    nunjcrT1a5HIdzgilAOeiaOCAkcwggJDMA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUE
    FjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU
    u9mag8gVOBttlIpDR6jct1X5cekwHwYDVR0jBBgwFoAUnytfzzwhT50Et+0rLMTG
    cIvS1w0wVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVodHRwOi8vZTUuby5s
    ZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9lNS5pLmxlbmNyLm9yZy8wIgYD
    VR0RBBswGYIXKi5jb25zaWxpdW0uZHVja2Rucy5vcmcwEwYDVR0gBAwwCjAIBgZn
    gQwBAgEwLQYDVR0fBCYwJDAioCCgHoYcaHR0cDovL2U1LmMubGVuY3Iub3JnLzUz
    LmNybDCCAQMGCisGAQQB1nkCBAIEgfQEgfEA7wB1AMz7D2qFcQll/pWbU87psnwi
    6YVcDZeNtql+VMD+TA2wAAABlhb8d7QAAAQDAEYwRAIgDIHJ7Hp90jKeaEoYx/wz
    3vkASS+EwaDg3Zoy/jf15RgCIHd6c/XDTND1QPVzWWjNGwtQC8sVAT+H1eIDG+tN
    VA4FAHYAouMK5EXvva2bfjjtR2d3U9eCW4SU1yteGyzEuVCkR+cAAAGWFvx/cQAA
    BAMARzBFAiAA5+e4qxEij2jqX1k1f/mTrux4U46u/TxCtDa2c5f06AIhAKbNMJ2j
    DSC0UWKoAjXKwRCz8PKMCTXZegmdwXcuJhOQMAoGCCqGSM49BAMDA2kAMGYCMQCH
    OCIi4+C4n5pLEV61FhrVQqUqqTSOC3WGoG66I2i0cYv5haOzR7FNkBdjXI6ZmgoC
    MQCbntS5Vs3p95yIk3oDYeE6u6rnzHLT8rib/s+Lkv+T1P+VNyhjt4tY5VRJ9bLt
    2hM=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIEVzCCAj+gAwIBAgIRAIOPbGPOsTmMYgZigxXJ/d4wDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjQwMzEzMDAwMDAw
    WhcNMjcwMzEyMjM1OTU5WjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
    RW5jcnlwdDELMAkGA1UEAxMCRTUwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAQNCzqK
    a2GOtu/cX1jnxkJFVKtj9mZhSAouWXW0gQI3ULc/FnncmOyhKJdyIBwsz9V8UiBO
    VHhbhBRrwJCuhezAUUE8Wod/Bk3U/mDR+mwt4X2VEIiiCFQPmRpM5uoKrNijgfgw
    gfUwDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
    ATASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBSfK1/PPCFPnQS37SssxMZw
    i9LXDTAfBgNVHSMEGDAWgBR5tFnme7bl5AFzgAiIyBpY9umbbjAyBggrBgEFBQcB
    AQQmMCQwIgYIKwYBBQUHMAKGFmh0dHA6Ly94MS5pLmxlbmNyLm9yZy8wEwYDVR0g
    BAwwCjAIBgZngQwBAgEwJwYDVR0fBCAwHjAcoBqgGIYWaHR0cDovL3gxLmMubGVu
    Y3Iub3JnLzANBgkqhkiG9w0BAQsFAAOCAgEAH3KdNEVCQdqk0LKyuNImTKdRJY1C
    2uw2SJajuhqkyGPY8C+zzsufZ+mgnhnq1A2KVQOSykOEnUbx1cy637rBAihx97r+
    bcwbZM6sTDIaEriR/PLk6LKs9Be0uoVxgOKDcpG9svD33J+G9Lcfv1K9luDmSTgG
    6XNFIN5vfI5gs/lMPyojEMdIzK9blcl2/1vKxO8WGCcjvsQ1nJ/Pwt8LQZBfOFyV
    XP8ubAp/au3dc4EKWG9MO5zcx1qT9+NXRGdVWxGvmBFRAajciMfXME1ZuGmk3/GO
    koAM7ZkjZmleyokP1LGzmfJcUd9s7eeu1/9/eg5XlXd/55GtYjAM+C4DG5i7eaNq
    cm2F+yxYIPt6cbbtYVNJCGfHWqHEQ4FYStUyFnv8sjyqU8ypgZaNJ9aVcWSICLOI
    E1/Qv/7oKsnZCWJ926wU6RqG1OYPGOi1zuABhLw61cuPVDT28nQS/e6z95cJXq0e
    K1BcaJ6fJZsmbjRgD5p3mvEf5vdQM7MCEvU0tHbsx2I5mHHJoABHb8KVBgWp/lcX
    GWiWaeOyB7RP+OfDtvi2OsapxXiV7vNVs7fMlrRjY1joKaqmmycnBvAq14AEbtyL
    sVfOS66B8apkeFX2NY4XPEYV4ZSCe8VHPrdrERk2wILG3T/EGmSIkCYVUMSnjmJd
    VQD9F6Na/+zmXCc=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgmJiDbyC+KyJmzNyT
    IvUQqoL1SW64GpMdSeBDG5CnTPyhRANCAAQw3oQts0edWNnifuH6dgqEmcinlqdS
    GC/7+bMAmy4CJG9UZRk2DYkqMY2g1awXL/Ke6eNytPVrkch3OCKUA56J
    -----END PRIVATE KEY-----