@Consilium = http://localhost:5202
@email = bob@example.com
@key = qrFNrl4wiS5iCUWrsFCx

###
GET {{Consilium}}/account
###
POST {{Consilium}}/account?email={{email}}
### Get to-do lists
GET {{Consilium}}/todo
Email-Auth_Email: {{email}}
###
GET {{Consilium}}/todo/2/items
Email-Auth_Email: {{email}}
###
POST {{Consilium}}/todo
Email-Auth_Email: {{email}}
Content-Type: application/json
{
  "id": 2,
  "title": "Lorem2",
  "isCompleted": false,
  "todoListId": 2,
  "parentId": null,
  "category": "Something else"
}
###
PATCH {{Consilium}}/todo/update
Email-Auth_Email: {{email}}
Content-Type: application/json
{
  "id": 4,
  "isCompleted": true
}


