@Consilium = http://localhost:5202


###
GET {{Consilium}}/todo
Consilium-User: cody
###
PATCH {{Consilium}}/todo?index=0
Consilium-User: cody
Content-Type: application/json
  {
    "title": "New",
    "description": null,
    "category": null,
    "isCompleted": false,
    "subTasks": []
  }
###

