services:
  db:
    container_name: consilium-db
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: consilium-admin
      POSTGRES_DB: consiliumdb
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
      # - ./dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432