# https://shipit.dev/posts/trigger-github-actions-on-pr-close.html
name: Close Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  delete_enviroment:
    runs-on: self-hosted
    steps:
    - name: Delete Namespace with all contents
      run: kubectl delete namespace consilium-pull-request-${{github.event.number}}