name: BackUp Database

on:
- workflow_dispatch

jobs:
  BackUp:
    runs-on: self-hosted
    steps:
        - name: Set Namespace
          run: kubectl config set-context --current --namespace=consilium

        - name: Get current pod name
          id: get-pod
          run: |
            POD_NAME=$(kubectl get pods -l app=consilium-postgres -o jsonpath='{.items[0].metadata.name}')
            echo "POD_NAME=$POD_NAME" >> $GITHUB_ENV
  
        - name: Delete Oldest Back Up & Create New Back Up
          run: |
            kubectl exec -it $POD_NAME -- bash -c '
              BACKUP_DIR="/var/backups"
              ls -1t "$BACKUP_DIR"/*_backup.sql 2>/dev/null | tail -n +4 | xargs -r rm --
              pg_dump -U consilium-admin consiliumdb > "$BACKUP_DIR/$(date +%Y-%m-%d_%H%M)_backup.sql"
            '
            